name: Create Preview

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Delete all files except hidden files
        run: rm -rfv *
      - name: Clone jaoafa/jaoweb
        run: |
          git clone https://github.com/jaoafa/jaoweb
          rm -rfv jaoweb/content/
          cd jaoweb
      - name: Clone all Branches
        run: |
          cd jaoweb
          curl "https://api.github.com/repos/jaoafa/jaoweb-docs/branches" \
            | jq -r .[].name \
            | xargs -L 1 -I {} \
            sh -c "git clone -b {} https://github.com/jaoafa/jaoweb-docs content/ && rm -rf node_modules dist ; export BASE_URL=https://book000.github.io/jaoweb-docs/{} && yarn install && yarn generate && mv -v dist ../{}"
        env:
          NUXT_TELEMETRY_DISABLED: 1
      - name: Delete gh-pages
        run: rm -rf gh-pages ; return 0
      - name: Delete jaoafa/jaoweb
        run: |
          rm -rf jaoweb
      - name: Checkout branch & Commit files
        run: |
          git add -A
          git config --local user.name "Preview Bot"
          git config --local user.email secret.EMAIL
          git checkout -b gh-pages
          git commit -v -m "[Bot] Auto build $(date +'%Y-%m-%d')"
          git push origin gh-pages -f
